name: build-push-docker

on:
  push:
    # branches:
    #   - 'main'
    paths:
      - .github/workflows/build-docker.yaml
      - 'docker/**'

env:
  IMAGE_PREFIX: kalioz/test-nginx-autobuild

jobs:
  docker:
    uses: kalioz-github-action/github-actions/.github/workflows/reusable_docker_build.yaml@cloiselet/reusable-workflow-docker-build
    with:
      context: "docker"
      dockerfile: "docker/Dockerfile"
      use_docker_in_docker: false # quicker build, but need to be used in self-hosted runners.
    secrets:
      DOCKERHUB_USER: "${{ secrets.DOCKERHUB_USER }}"
      DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"