name: build-push-docker

on:
  push:
    branches:
      - build-docker
    paths:
      - .github/workflows/build-docker.yml
      - docker/*

env:
  IMAGE_PREFIX: kalioz/test-nginx-autobuild
  DOCKERFILE: docker/Dockerfile

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ${{ env.DOCKERFILE }}

  docker-build:
    runs-on: ubuntu-latest
    needs: docker-lint
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: get version
        run: echo "VERSION=$(cat docker/VERSION)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:latest
            ${{ env.IMAGE_PREFIX }}:${{ env.VERSION }}